server:
  port: ${SERVER_PORT:8080}
wemq:
  nmqs:
    host: ${NMQS_HOST:localhost}
    port: ${NMQS_PORT:8081}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:wemq}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.mmanager.model
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true
logging:
  file:
    name: logs/logs.log
  level:
      root: info
      cn.mmanager: debug
